/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_leehangeol_sakamaka_ARactivity */

#ifndef _Included_com_example_leehangeol_sakamaka_ARactivity
#define _Included_com_example_leehangeol_sakamaka_ARactivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_leehangeol_sakamaka_ARactivity_MIN_OPENGL_VERSION
#define com_example_leehangeol_sakamaka_ARactivity_MIN_OPENGL_VERSION 3.0
/*
 * Class:     com_example_leehangeol_sakamaka_ARactivity
 * Method:    loadImage
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_example_leehangeol_sakamaka_ARactivity_loadImage
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_example_leehangeol_sakamaka_ARactivity
 * Method:    imageprocessing
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_leehangeol_sakamaka_ARactivity_imageprocessing
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
